import type { CategoryTree } from '@/types/new/new_form_schema';

// cascaderTree
export const categoryTree: CategoryTree = {
  aroma: [
    {
      id: 1,
      label: '꽃',
      value: 'aroma_floral',
      children: [
        {
          id: 1,
          label: '화이트 플라워',
          value: 'white',
          children: [
            { id: 1, label: '자스민', value: 'jasmine' },
            { id: 2, label: '백합', value: 'lily' },
            { id: 3, label: '박하', value: 'mint' },
            { id: 4, label: '민들레', value: 'dandelion' },
            { id: 5, label: '동백', value: 'camellia' },
          ],
        },
        {
          id: 2,
          label: '장미',
          value: 'rose',
          children: [
            { id: 1, label: '에덴', value: 'eden' },
            { id: 2, label: '아이스버그', value: 'iceberg' },
            { id: 3, label: '엘', value: 'elle' },
            { id: 4, label: '센티멘털', value: 'scentimental' },
            { id: 5, label: '로열', value: 'royal' },
          ],
        },
        {
          id: 3,
          label: '자스민',
          value: 'jasmine',
          children: [
            { id: 1, label: '아라비안 자스민', value: 'arabian' },
            { id: 2, label: '그랜드 자스민', value: 'grand' },
            { id: 3, label: '피카케 자스민', value: 'pikake' },
            { id: 4, label: '화이트 자스민', value: 'white' },
            { id: 5, label: '사라 자스민', value: 'sara' },
          ],
        },
        {
          id: 4,
          label: '플라워',
          value: 'flower',
          children: [
            { id: 1, label: '라벤더', value: 'lavender' },
            { id: 2, label: '프리지아', value: 'freesia' },
            { id: 3, label: '아이리스', value: 'iris' },
            { id: 4, label: '라일락', value: 'lilac' },
            { id: 5, label: '데이지', value: 'daisy' },
          ],
        },
        {
          id: 5,
          label: '허벌·그린',
          value: 'green',
          children: [
            { id: 1, label: '민트', value: 'mint' },
            { id: 2, label: '로즈메리', value: 'rosemary' },
            { id: 3, label: '세이지', value: 'sage' },
            { id: 4, label: '바질', value: 'basil' },
            { id: 5, label: '유칼립투스', value: 'eucalyptus' },
          ],
        },
      ],
    },
    {
      id: 2,
      label: '과일',
      value: 'aroma_fruity',
      children: [
        {
          id: 1,
          label: '시트러스',
          value: 'citrus',
          children: [
            { id: 1, label: '오렌지', value: 'orange' },
            { id: 2, label: '레몬', value: 'lemon' },
            { id: 3, label: '자몽', value: 'grapefruit' },
            { id: 4, label: '라임', value: 'lime' },
            { id: 5, label: '유자', value: 'yuja' },
          ],
        },
        {
          id: 2,
          label: '베리',
          value: 'berry',
          children: [
            { id: 1, label: '딸기', value: 'strawberry' },
            { id: 2, label: '블루베리', value: 'blueberry' },
            { id: 3, label: '라즈베리', value: 'raspberry' },
            { id: 4, label: '블랙베리', value: 'blackberry' },
            { id: 5, label: '크랜베리', value: 'cranberry' },
          ],
        },
        {
          id: 3,
          label: '열대과일',
          value: 'tropical',
          children: [
            { id: 1, label: '망고', value: 'mango' },
            { id: 2, label: '파인애플', value: 'pineapple' },
            { id: 3, label: '패션프루트', value: 'passionfruit' },
            { id: 4, label: '바나나', value: 'banana' },
            { id: 5, label: '코코넛', value: 'coconut' },
          ],
        },
        {
          id: 4,
          label: '건과일',
          value: 'dried',
          children: [
            { id: 1, label: '건자두', value: 'prune' },
            { id: 2, label: '건포도', value: 'raisin' },
            { id: 3, label: '무화과', value: 'fig' },
            { id: 4, label: '대추', value: 'date' },
            { id: 5, label: '말린 살구', value: 'apricot' },
          ],
        },
        {
          id: 5,
          label: '사과·배',
          value: 'apple',
          children: [
            { id: 1, label: '사과', value: 'apple' },
            { id: 2, label: '배', value: 'pear' },
            { id: 3, label: '복숭아', value: 'peach' },
            { id: 4, label: '자두', value: 'plum' },
            { id: 5, label: '살구', value: 'apricot' },
          ],
        },
      ],
    },
    {
      id: 3,
      label: '향신료',
      value: 'aroma_spicy',
      children: [
        {
          id: 1,
          label: '따뜻한 향신료',
          value: 'warm',
          children: [
            { id: 1, label: '시나몬', value: 'cinnamon' },
            { id: 2, label: '넛메그', value: 'nutmeg' },
            { id: 3, label: '클로브', value: 'clove' },
            { id: 4, label: '올스파이스', value: 'allspice' },
            { id: 5, label: '카다멈', value: 'cardamom' },
          ],
        },
        {
          id: 2,
          label: '매운 향신료',
          value: 'hot',
          children: [
            { id: 1, label: '후추', value: 'pepper' },
            { id: 2, label: '칠리', value: 'chili' },
            { id: 3, label: '생강', value: 'ginger' },
            { id: 4, label: '겨자', value: 'mustard' },
            { id: 5, label: '커민', value: 'cumin' },
          ],
        },
        {
          id: 3,
          label: '허브',
          value: 'herb',
          children: [
            { id: 1, label: '타임', value: 'thyme' },
            { id: 2, label: '오레가노', value: 'oregano' },
            { id: 3, label: '딜', value: 'dill' },
            { id: 4, label: '페넬', value: 'fennel' },
            { id: 5, label: '커리잎', value: 'curry_leaf' },
          ],
        },
      ],
    },
    {
      id: 4,
      label: '티·블라썸',
      value: 'aroma_tea',
      children: [
        {
          id: 1,
          label: '블랙티',
          value: 'black',
          children: [
            { id: 1, label: '다질링', value: 'darjeeling' },
            { id: 2, label: '아삼', value: 'assam' },
            { id: 3, label: '실론', value: 'ceylon' },
            { id: 4, label: '얼그레이', value: 'earlgrey' },
            {
              id: 5,
              label: '잉글리시브렉퍼스트',
              value: 'english_breakfast',
            },
          ],
        },
        {
          id: 2,
          label: '그린티',
          value: 'green',
          children: [
            { id: 1, label: '센차', value: 'sencha' },
            { id: 2, label: '말차', value: 'matcha' },
            { id: 3, label: '자스민그린', value: 'jasmine' },
            { id: 4, label: '현미녹차', value: 'genmaicha' },
            { id: 5, label: '룽징', value: 'longjing' },
          ],
        },
        {
          id: 3,
          label: '우롱',
          value: 'oolong',
          children: [
            { id: 1, label: '철관음', value: 'tieguanyin' },
            { id: 2, label: '동방미인', value: 'oriental_beauty' },
            { id: 3, label: '밀크우롱', value: 'milk' },
            { id: 4, label: '봉황단총', value: 'phoenix' },
            { id: 5, label: '대만고산', value: 'high_mountain' },
          ],
        },
        {
          id: 4,
          label: '허브티',
          value: 'herbal',
          children: [
            { id: 1, label: '캐모마일', value: 'chamomile' },
            { id: 2, label: '히비스커스', value: 'hibiscus' },
            { id: 3, label: '루이보스', value: 'rooibos' },
            { id: 4, label: '레몬그라스', value: 'lemongrass' },
            { id: 5, label: '페퍼민트', value: 'peppermint' },
          ],
        },
        {
          id: 5,
          label: '블라썸',
          value: 'blossom',
          children: [
            { id: 1, label: '체리블라썸', value: 'cherry' },
            { id: 2, label: '오렌지블라썸', value: 'orange' },
            { id: 3, label: '복숭아블라썸', value: 'peach' },
            { id: 4, label: '자두블라썸', value: 'plum' },
            { id: 5, label: '아몬드블라썸', value: 'almond' },
          ],
        },
      ],
    },
    {
      id: 5,
      label: '오키드·바이올렛',
      value: 'aroma_orchid_violet',
      children: [
        {
          id: 1,
          label: '오키드',
          value: 'orchid',
          children: [
            { id: 1, label: '화이트오키드', value: 'white' },
            { id: 2, label: '바닐라오키드', value: 'vanilla' },
            { id: 3, label: '핑크오키드', value: 'pink' },
            { id: 4, label: '덴드로비움', value: 'dendrobium' },
            { id: 5, label: '카틀레야', value: 'cattleya' },
          ],
        },
        {
          id: 2,
          label: '바이올렛',
          value: 'violet',
          children: [
            { id: 1, label: '스위트바이올렛', value: 'sweet' },
            { id: 2, label: '아이오니아', value: 'ionone' },
            { id: 3, label: '바이올렛리프', value: 'leaf' },
            { id: 4, label: '바이올렛캔디', value: 'candy' },
            { id: 5, label: '바이올렛파우더', value: 'powder' },
          ],
        },
        {
          id: 3,
          label: '피오니',
          value: 'peony',
          children: [
            { id: 1, label: '코랄피오니', value: 'coral' },
            { id: 2, label: '핑크피오니', value: 'pink' },
            { id: 3, label: '화이트피오니', value: 'white' },
            { id: 4, label: '트리피오니', value: 'tree' },
            { id: 5, label: '프레시피오니', value: 'fresh' },
          ],
        },
        {
          id: 4,
          label: '매화',
          value: 'plum',
          children: [
            { id: 1, label: '백매', value: 'white' },
            { id: 2, label: '홍매', value: 'red' },
            { id: 3, label: '청매', value: 'green' },
            { id: 4, label: '매화향', value: 'scent' },
            { id: 5, label: '만개매화', value: 'full_bloom' },
          ],
        },
        {
          id: 5,
          label: '수선화',
          value: 'narcissus',
          children: [
            { id: 1, label: '나르시수스', value: 'narcissus' },
            { id: 2, label: '화이트수선화', value: 'white' },
            { id: 3, label: '옐로우수선화', value: 'yellow' },
            { id: 4, label: '더블수선화', value: 'double' },
            { id: 5, label: '페이퍼화이트', value: 'paperwhite' },
          ],
        },
      ],
    },
  ],
  taste: [
    {
      id: 1,
      label: '쓴맛',
      value: 'taste_bitterness',
      children: [
        {
          id: 1,
          label: '코코아·커피',
          value: 'cocoa_coffee',
          children: [
            { id: 1, label: '코코아닙', value: 'cocoa_nib' },
            { id: 2, label: '다크초콜릿', value: 'dark_chocolate' },
            { id: 3, label: '에스프레소', value: 'espresso' },
            { id: 4, label: '카카오허스크', value: 'cacao_husk' },
            { id: 5, label: '베이킹초콜릿', value: 'baking_chocolate' },
          ],
        },
        {
          id: 2,
          label: '허벌·식물성',
          value: 'herbal_bitter',
          children: [
            { id: 1, label: '겐티안', value: 'gentian' },
            { id: 2, label: '웜우드', value: 'wormwood' },
            { id: 3, label: '민들레뿌리', value: 'dandelion_root' },
            { id: 4, label: '치커리', value: 'chicory' },
            { id: 5, label: '말차', value: 'matcha' },
          ],
        },
        {
          id: 3,
          label: '로스티드',
          value: 'roasted_bitter',
          children: [
            { id: 1, label: '차콜', value: 'char' },
            { id: 2, label: '탄 토스트', value: 'burnt_toast' },
            { id: 3, label: '스모크', value: 'smoke' },
            { id: 4, label: '애쉬', value: 'ash' },
            { id: 5, label: '오버로스티드넛', value: 'over_roasted_nut' },
          ],
        },
        {
          id: 4,
          label: '타닌',
          value: 'tannin',
          children: [
            { id: 1, label: '블랙티', value: 'black_tea_tannin' },
            { id: 2, label: '레드와인타닌', value: 'red_wine_tannin' },
            { id: 3, label: '호두껍질', value: 'walnut_skin' },
            { id: 4, label: '포도씨', value: 'grape_seed' },
            { id: 5, label: '오크', value: 'oak' },
          ],
        },
        {
          id: 5,
          label: '퀴닌·홉',
          value: 'quinine_hops',
          children: [
            { id: 1, label: '토닉워터', value: 'tonic' },
            { id: 2, label: '자몽피스', value: 'grapefruit_pith' },
            { id: 3, label: '홉', value: 'hops' },
            { id: 4, label: '퀴닌', value: 'quinine' },
            { id: 5, label: '콜라넛', value: 'kola_nut' },
          ],
        },
      ],
    },
    {
      id: 2,
      label: '짠맛',
      value: 'taste_saltiness',
      children: [
        {
          id: 1,
          label: '미네랄',
          value: 'mineral',
          children: [
            { id: 1, label: '미네랄워터', value: 'mineral_water' },
            { id: 2, label: '락솔트', value: 'rock_salt' },
            { id: 3, label: '슬레이트', value: 'slate' },
            { id: 4, label: '초크', value: 'chalk' },
            { id: 5, label: '세일린', value: 'saline' },
          ],
        },
        {
          id: 2,
          label: '해양',
          value: 'sea',
          children: [
            { id: 1, label: '씨솔트', value: 'sea_salt' },
            { id: 2, label: '바다바람', value: 'sea_breeze' },
            { id: 3, label: '노리솔트', value: 'nori_salt' },
            { id: 4, label: '앤초비솔트', value: 'anchovy_salt' },
            { id: 5, label: '브라인', value: 'brine' },
          ],
        },
        {
          id: 3,
          label: '브로스',
          value: 'broth',
          children: [
            { id: 1, label: '라이트브로스', value: 'light_broth' },
            { id: 2, label: '치킨브로스', value: 'chicken_broth' },
            { id: 3, label: '베지터블스톡', value: 'vegetable_stock' },
            { id: 4, label: '미소수프', value: 'miso_soup' },
            { id: 5, label: '다시', value: 'dashi' },
          ],
        },
        {
          id: 4,
          label: '발효계 짠맛',
          value: 'fermented_salty',
          children: [
            { id: 1, label: '간장', value: 'soy_sauce' },
            { id: 2, label: '피시소스', value: 'fish_sauce' },
            { id: 3, label: '피클브라인', value: 'pickled_brine' },
            { id: 4, label: '김치브라인', value: 'kimchi_brine' },
            { id: 5, label: '올리브브라인', value: 'olive_brine' },
          ],
        },
        {
          id: 5,
          label: '치즈계',
          value: 'cheesy_salty',
          children: [
            { id: 1, label: '파르미지아노', value: 'parmesan' },
            { id: 2, label: '페코리노', value: 'pecorino' },
            { id: 3, label: '페타', value: 'feta' },
            { id: 4, label: '에이지드체다', value: 'aged_cheddar' },
            { id: 5, label: '블루치즈', value: 'blue_cheese' },
          ],
        },
      ],
    },
    {
      id: 3,
      label: '감칠맛',
      value: 'taste_umami',
      children: [
        {
          id: 1,
          label: '버섯',
          value: 'mushroom',
          children: [
            { id: 1, label: '표고', value: 'shiitake' },
            { id: 2, label: '포르치니', value: 'porcini' },
            { id: 3, label: '양송이', value: 'champignon' },
            { id: 4, label: '트러플', value: 'truffle' },
            { id: 5, label: '모렐', value: 'morel' },
          ],
        },
        {
          id: 2,
          label: '육향',
          value: 'meaty',
          children: [
            { id: 1, label: '비프브로스', value: 'beef_broth' },
            { id: 2, label: '햄', value: 'ham' },
            { id: 3, label: '프로슈토', value: 'prosciutto' },
            { id: 4, label: '로스트치킨', value: 'roast_chicken' },
            { id: 5, label: '그레이비', value: 'gravy' },
          ],
        },
        {
          id: 3,
          label: '발효',
          value: 'fermented',
          children: [
            { id: 1, label: '미소', value: 'miso' },
            { id: 2, label: '간장', value: 'soy_sauce' },
            { id: 3, label: '된장', value: 'doenjang' },
            { id: 4, label: '고추장', value: 'gochujang' },
            { id: 5, label: '가쓰오부시', value: 'katsuobushi' },
          ],
        },
        {
          id: 4,
          label: '해조',
          value: 'seaweed',
          children: [
            { id: 1, label: '곤부', value: 'kombu' },
            { id: 2, label: '노리', value: 'nori' },
            { id: 3, label: '와카메', value: 'wakame' },
            { id: 4, label: '켈프', value: 'kelp' },
            { id: 5, label: '히지키', value: 'hijiki' },
          ],
        },
        {
          id: 5,
          label: '에이징',
          value: 'aged',
          children: [
            { id: 1, label: '파르미지아노껍질', value: 'parmesan_rind' },
            { id: 2, label: '에이지드치즈', value: 'aged_cheese' },
            { id: 3, label: '가쓰오부시', value: 'bonito_flake' },
            { id: 4, label: '마마이트', value: 'marmite' },
            { id: 5, label: 'XO소스', value: 'xo_sauce' },
          ],
        },
      ],
    },
    {
      id: 4,
      label: '구수함',
      value: 'taste_toasty',
      children: [
        {
          id: 1,
          label: '곡물',
          value: 'grain',
          children: [
            { id: 1, label: '보리', value: 'barley' },
            { id: 2, label: '현미', value: 'brown_rice' },
            { id: 3, label: '옥수수', value: 'corn' },
            { id: 4, label: '메밀', value: 'buckwheat' },
            { id: 5, label: '귀리', value: 'oat' },
          ],
        },
        {
          id: 2,
          label: '고소견과',
          value: 'nutty',
          children: [
            { id: 1, label: '땅콩', value: 'peanut' },
            { id: 2, label: '아몬드', value: 'almond' },
            { id: 3, label: '캐슈', value: 'cashew' },
            { id: 4, label: '해바라기씨', value: 'sunflower_seed' },
            { id: 5, label: '참깨', value: 'sesame' },
          ],
        },
        {
          id: 3,
          label: '맥아·토스트',
          value: 'malt_toast',
          children: [
            { id: 1, label: '라이트토스트', value: 'light_toast' },
            { id: 2, label: '미디엄토스트', value: 'medium_toast' },
            { id: 3, label: '다크토스트', value: 'dark_toast' },
            { id: 4, label: '맥아', value: 'malt' },
            { id: 5, label: '그래놀라', value: 'granola' },
          ],
        },
        {
          id: 4,
          label: '곡물음료',
          value: 'grain_drink',
          children: [
            { id: 1, label: '보리차', value: 'barley_tea' },
            { id: 2, label: '옥수수수염차', value: 'corn_silk_tea' },
            { id: 3, label: '현미차', value: 'brown_rice_tea' },
            { id: 4, label: '미숫가루', value: 'misugaru' },
            { id: 5, label: '식혜', value: 'sikhye' },
          ],
        },
        {
          id: 5,
          label: '곡분·반죽',
          value: 'doughy_cereal',
          children: [
            { id: 1, label: '반죽향', value: 'dough' },
            { id: 2, label: '비스킷', value: 'biscuit' },
            { id: 3, label: '크래커', value: 'cracker' },
            { id: 4, label: '도우', value: 'bread_dough' },
            { id: 5, label: '누룽지', value: 'scorched_rice' },
          ],
        },
      ],
    },
    {
      id: 5,
      label: '스모키',
      value: 'taste_smoky',
      children: [
        {
          id: 1,
          label: '우디 스모크',
          value: 'woody_smoke',
          children: [
            { id: 1, label: '장작', value: 'firewood' },
            { id: 2, label: '히코리', value: 'hickory' },
            { id: 3, label: '오크', value: 'oak_wood' },
            { id: 4, label: '삼나무', value: 'cedar' },
            { id: 5, label: '숯', value: 'charcoal' },
          ],
        },
        {
          id: 2,
          label: '타르·레진',
          value: 'tar_resin',
          children: [
            { id: 1, label: '타르', value: 'tar' },
            { id: 2, label: '역청', value: 'bitumen' },
            { id: 3, label: '송진', value: 'pine_resin' },
            { id: 4, label: '수지', value: 'resin' },
            { id: 5, label: '석탄가루', value: 'coal_dust' },
          ],
        },
        {
          id: 3,
          label: '훈연식품',
          value: 'smoked_food',
          children: [
            { id: 1, label: '훈제베이컨', value: 'smoked_bacon' },
            { id: 2, label: '훈제치즈', value: 'smoked_cheese' },
            { id: 3, label: '훈제넛', value: 'smoked_nut' },
            { id: 4, label: '훈제소금', value: 'smoked_salt' },
            { id: 5, label: '라프산소총', value: 'lapsang_souchong' },
          ],
        },
        {
          id: 4,
          label: '재·그을음',
          value: 'ash_soot',
          children: [
            { id: 1, label: '잿내', value: 'ashy' },
            { id: 2, label: '그을음', value: 'soot' },
            { id: 3, label: '재비', value: 'cinder' },
            { id: 4, label: '탄내', value: 'burnt' },
            { id: 5, label: '소각향', value: 'incinerated' },
          ],
        },
        {
          id: 5,
          label: '담배·가죽',
          value: 'tobacco_leather',
          children: [
            { id: 1, label: '시가', value: 'cigar' },
            { id: 2, label: '담배잎', value: 'tobacco_leaf' },
            { id: 3, label: '파이프스모크', value: 'pipe_smoke' },
            { id: 4, label: '가죽', value: 'leather' },
            { id: 5, label: '새들가죽', value: 'saddle_leather' },
          ],
        },
      ],
    },
  ],
  acidity: [
    {
      id: 1,
      label: '시트러스',
      value: 'acidity_citrus',
      children: [
        {
          id: 1,
          label: '레몬',
          value: 'lemon',
          children: [
            { id: 1, label: '레몬', value: 'lemon' },
            { id: 2, label: '라임', value: 'lime' },
            { id: 3, label: '유자', value: 'yuzu' },
            { id: 4, label: '청귤', value: 'green_mandarin' },
            { id: 5, label: '베르가못', value: 'bergamot' },
          ],
        },
        {
          id: 2,
          label: '오렌지',
          value: 'orange',
          children: [
            { id: 1, label: '오렌지', value: 'orange' },
            { id: 2, label: '자몽', value: 'grapefruit' },
            { id: 3, label: '탠저린', value: 'tangerine' },
            { id: 4, label: '만다린', value: 'mandarin' },
            { id: 5, label: '블러드오렌지', value: 'blood_orange' },
          ],
        },
        {
          id: 3,
          label: '열대과일',
          value: 'tropical',
          children: [
            { id: 1, label: '파인애플', value: 'pineapple' },
            { id: 2, label: '패션프루트', value: 'passionfruit' },
            { id: 3, label: '망고', value: 'mango' },
            { id: 4, label: '파파야', value: 'papaya' },
            { id: 5, label: '리치', value: 'lychee' },
          ],
        },
        {
          id: 4,
          label: '신선한 과일',
          value: 'fresh_fruit',
          children: [
            { id: 1, label: '사과', value: 'apple' },
            { id: 2, label: '배', value: 'pear' },
            { id: 3, label: '포도', value: 'grape' },
            { id: 4, label: '체리', value: 'cherry' },
            { id: 5, label: '복숭아', value: 'peach' },
          ],
        },
        {
          id: 5,
          label: '베리',
          value: 'berry',
          children: [
            { id: 1, label: '크랜베리', value: 'cranberry' },
            { id: 2, label: '라즈베리', value: 'raspberry' },
            { id: 3, label: '블루베리', value: 'blueberry' },
            { id: 4, label: '블랙커런트', value: 'blackcurrant' },
            { id: 5, label: '구스베리', value: 'gooseberry' },
          ],
        },
      ],
    },
    {
      id: 2,
      label: '말릭',
      value: 'acidity_malic',
      children: [
        {
          id: 1,
          label: '그린애플',
          value: 'green_apple',
          children: [
            { id: 1, label: '풋사과', value: 'unripe_apple' },
            { id: 2, label: '사과껍질', value: 'apple_peel' },
            { id: 3, label: '사과즙', value: 'apple_juice' },
            { id: 4, label: '사과식초', value: 'apple_vinegar' },
            { id: 5, label: '사과캔디', value: 'apple_candy' },
          ],
        },
        {
          id: 2,
          label: '배',
          value: 'pear',
          children: [
            { id: 1, label: '배', value: 'pear' },
            { id: 2, label: '모과', value: 'quince' },
            { id: 3, label: '서양배', value: 'western_pear' },
            { id: 4, label: '유럽배', value: 'european_pear' },
            { id: 5, label: '아시아배', value: 'asian_pear' },
          ],
        },
        {
          id: 3,
          label: '포도',
          value: 'grape',
          children: [
            { id: 1, label: '화이트그레이프', value: 'white_grape' },
            { id: 2, label: '적포도', value: 'red_grape' },
            { id: 3, label: '청포도', value: 'green_grape' },
            { id: 4, label: '건포도', value: 'raisin' },
            { id: 5, label: '포도즙', value: 'grape_juice' },
          ],
        },
        {
          id: 4,
          label: '플럼·체리',
          value: 'plum_cherry',
          children: [
            { id: 1, label: '자두', value: 'plum' },
            { id: 2, label: '체리', value: 'cherry' },
            { id: 3, label: '사워체리', value: 'sour_cherry' },
            { id: 4, label: '블랙체리', value: 'black_cherry' },
            { id: 5, label: '자두껍질', value: 'plum_skin' },
          ],
        },
        {
          id: 5,
          label: '베리',
          value: 'berry',
          children: [
            { id: 1, label: '딸기', value: 'strawberry' },
            { id: 2, label: '라즈베리', value: 'raspberry' },
            { id: 3, label: '크랜베리', value: 'cranberry' },
            { id: 4, label: '블랙베리', value: 'blackberry' },
            { id: 5, label: '커런트', value: 'currant' },
          ],
        },
      ],
    },
    {
      id: 3,
      label: '타르타릭',
      value: 'acidity_tartaric',
      children: [
        {
          id: 1,
          label: '와인',
          value: 'wine',
          children: [
            { id: 1, label: '화이트와인', value: 'white_wine' },
            { id: 2, label: '레드와인', value: 'red_wine' },
            { id: 3, label: '로제와인', value: 'rose_wine' },
            { id: 4, label: '스파클링와인', value: 'sparkling_wine' },
            { id: 5, label: '포트와인', value: 'port_wine' },
          ],
        },
        {
          id: 2,
          label: '건과일',
          value: 'dried_fruit',
          children: [
            { id: 1, label: '건자두', value: 'prune' },
            { id: 2, label: '건포도', value: 'raisin' },
            { id: 3, label: '말린살구', value: 'dried_apricot' },
            { id: 4, label: '말린무화과', value: 'dried_fig' },
            { id: 5, label: '건체리', value: 'dried_cherry' },
          ],
        },
        {
          id: 3,
          label: '포도',
          value: 'grape',
          children: [
            { id: 1, label: '버주스', value: 'verjus' },
            { id: 2, label: '포도껍질', value: 'grape_peel' },
            { id: 3, label: '포도씨', value: 'grape_seed' },
            { id: 4, label: '청포도즙', value: 'grape_juice' },
            { id: 5, label: '와인머스트', value: 'wine_must' },
          ],
        },
        {
          id: 4,
          label: '시큼한 과즙',
          value: 'tangy_juice',
          children: [
            { id: 1, label: '석류', value: 'pomegranate' },
            { id: 2, label: '타마린드', value: 'tamarind' },
            { id: 3, label: '감귤', value: 'mandarin_orange' },
            { id: 4, label: '포멜로', value: 'pomelo' },
            { id: 5, label: '사워체리즙', value: 'sour_cherry_juice' },
          ],
        },
        {
          id: 5,
          label: '산포화감',
          value: 'crisp_tart',
          children: [
            { id: 1, label: '상큼한', value: 'crisp' },
            { id: 2, label: '시큼한', value: 'tart' },
            { id: 3, label: '깔끔한', value: 'clean' },
            { id: 4, label: '산뜻한', value: 'fresh' },
            { id: 5, label: '날카로운', value: 'sharp' },
          ],
        },
      ],
    },
    {
      id: 4,
      label: '아세틱',
      value: 'acidity_acetic',
      children: [
        {
          id: 1,
          label: '발효산미',
          value: 'fermented_acid',
          children: [
            { id: 1, label: '식초', value: 'vinegar' },
            { id: 2, label: '사과식초', value: 'apple_vinegar' },
            { id: 3, label: '발사믹식초', value: 'balsamic' },
            { id: 4, label: '포도식초', value: 'grape_vinegar' },
            { id: 5, label: '와인비네거', value: 'wine_vinegar' },
          ],
        },
        {
          id: 2,
          label: '발효음료',
          value: 'fermented_drink',
          children: [
            { id: 1, label: '콤부차', value: 'kombucha' },
            { id: 2, label: '사워비어', value: 'sour_beer' },
            { id: 3, label: '사워사케', value: 'sour_sake' },
            { id: 4, label: '요거트드링크', value: 'yogurt_drink' },
            { id: 5, label: '라씨', value: 'lassi' },
          ],
        },
        {
          id: 3,
          label: '피클',
          value: 'pickle',
          children: [
            { id: 1, label: '오이피클', value: 'cucumber_pickle' },
            { id: 2, label: '무피클', value: 'radish_pickle' },
            { id: 3, label: '양파피클', value: 'onion_pickle' },
            { id: 4, label: '김치', value: 'kimchi' },
            { id: 5, label: '사워크라우트', value: 'sauerkraut' },
          ],
        },
        {
          id: 4,
          label: '사워도우',
          value: 'sourdough',
          children: [
            { id: 1, label: '사워도우', value: 'sourdough' },
            { id: 2, label: '천연효모', value: 'natural_yeast' },
            { id: 3, label: '발효빵', value: 'fermented_bread' },
            { id: 4, label: '요거트빵', value: 'yogurt_bread' },
            { id: 5, label: '루벤빵', value: 'reuben_bread' },
          ],
        },
        {
          id: 5,
          label: '식초향산미',
          value: 'vinegar_aroma',
          children: [
            { id: 1, label: '신맛강한', value: 'sharp_acid' },
            { id: 2, label: '톡쏘는', value: 'tingling' },
            { id: 3, label: '자극적인', value: 'pungent' },
            { id: 4, label: '매끈한산', value: 'smooth_acid' },
            { id: 5, label: '가벼운산', value: 'light_acid' },
          ],
        },
      ],
    },
    {
      id: 5,
      label: '락틱',
      value: 'acidity_lactic',
      children: [
        {
          id: 1,
          label: '유산발효',
          value: 'lactic_fermentation',
          children: [
            { id: 1, label: '요거트', value: 'yogurt' },
            { id: 2, label: '사워크림', value: 'sour_cream' },
            { id: 3, label: '버터밀크', value: 'buttermilk' },
            { id: 4, label: '리코타', value: 'ricotta' },
            { id: 5, label: '케피어', value: 'kefir' },
          ],
        },
        {
          id: 2,
          label: '치즈',
          value: 'cheesy_lactic',
          children: [
            { id: 1, label: '프레시치즈', value: 'fresh_cheese' },
            { id: 2, label: '크림치즈', value: 'cream_cheese' },
            { id: 3, label: '요거트치즈', value: 'yogurt_cheese' },
            { id: 4, label: '마스카포네', value: 'mascarpone' },
            { id: 5, label: '퀘소블랑코', value: 'queso_blanco' },
          ],
        },
        {
          id: 3,
          label: '버터·유제품',
          value: 'buttery_dairy',
          children: [
            { id: 1, label: '버터', value: 'butter' },
            { id: 2, label: '생크림', value: 'fresh_cream' },
            { id: 3, label: '우유', value: 'milk' },
            { id: 4, label: '연유', value: 'condensed_milk' },
            { id: 5, label: '요구르트', value: 'yogurt_drink' },
          ],
        },
        {
          id: 4,
          label: '부드러운 산미',
          value: 'soft_acid',
          children: [
            { id: 1, label: '크리미한', value: 'creamy' },
            { id: 2, label: '매끄러운', value: 'smooth' },
            { id: 3, label: '온화한', value: 'mild' },
            { id: 4, label: '부드러운', value: 'gentle' },
            { id: 5, label: '은은한', value: 'subtle' },
          ],
        },
        {
          id: 5,
          label: '요거트',
          value: 'yogurty',
          children: [
            { id: 1, label: '플레인요거트', value: 'plain_yogurt' },
            { id: 2, label: '그릭요거트', value: 'greek_yogurt' },
            { id: 3, label: '딸기요거트', value: 'strawberry_yogurt' },
            { id: 4, label: '복숭아요거트', value: 'peach_yogurt' },
            { id: 5, label: '꿀요거트', value: 'honey_yogurt' },
          ],
        },
      ],
    },
  ],
  switness: [
    {
      id: 1,
      label: '설탕',
      value: 'switness_sugar',
      children: [
        {
          id: 1,
          label: '정제당',
          value: 'refined_sugar',
          children: [
            { id: 1, label: '백설탕', value: 'white_sugar' },
            { id: 2, label: '분당', value: 'powdered_sugar' },
            { id: 3, label: '건당', value: 'rock_candy' },
            { id: 4, label: '큐브슈가', value: 'sugar_cube' },
            { id: 5, label: '설탕시럽', value: 'sugar_syrup' },
          ],
        },
        {
          id: 2,
          label: '비정제당',
          value: 'unrefined_sugar',
          children: [
            { id: 1, label: '황설탕', value: 'light_brown_sugar' },
            { id: 2, label: '흑설탕', value: 'dark_brown_sugar' },
            { id: 3, label: '머스코바도', value: 'muscovado' },
            { id: 4, label: '터비나도', value: 'turbinado' },
            { id: 5, label: '데메라라', value: 'demerara' },
          ],
        },
        {
          id: 3,
          label: '시럽',
          value: 'syrups',
          children: [
            { id: 1, label: '심플시럽', value: 'simple_syrup' },
            { id: 2, label: '골든시럽', value: 'golden_syrup' },
            { id: 3, label: '옥수수시럽', value: 'corn_syrup' },
            { id: 4, label: '글루코스시럽', value: 'glucose_syrup' },
            { id: 5, label: '아가베시럽', value: 'agave_syrup' },
          ],
        },
        {
          id: 4,
          label: '당밀',
          value: 'molasses',
          children: [
            { id: 1, label: '라이트몰라시스', value: 'light_molasses' },
            { id: 2, label: '다크몰라시스', value: 'dark_molasses' },
            { id: 3, label: '블랙스트랩', value: 'blackstrap_molasses' },
            { id: 4, label: '사탕수수당밀', value: 'cane_molasses' },
            { id: 5, label: '비트당밀', value: 'beet_molasses' },
          ],
        },
        {
          id: 5,
          label: '캔디',
          value: 'candies',
          children: [
            { id: 1, label: '하드캔디', value: 'hard_candy' },
            { id: 2, label: '롤리팝', value: 'lollipop' },
            { id: 3, label: '젤리빈', value: 'jelly_bean' },
            { id: 4, label: '프룻드롭', value: 'fruit_drop' },
            { id: 5, label: '퍼지', value: 'fudge' },
          ],
        },
      ],
    },
    {
      id: 2,
      label: '카라멜라이즈',
      value: 'switness_caramelized',
      children: [
        {
          id: 1,
          label: '카라멜',
          value: 'caramel',
          children: [
            { id: 1, label: '카라멜', value: 'caramel_core' },
            { id: 2, label: '솔티드카라멜', value: 'salted_caramel' },
            { id: 3, label: '카라멜소스', value: 'caramel_sauce' },
            { id: 4, label: '카라멜크림', value: 'caramel_cream' },
            { id: 5, label: '번트슈거', value: 'burnt_sugar' },
          ],
        },
        {
          id: 2,
          label: '토피',
          value: 'toffee',
          children: [
            { id: 1, label: '토피', value: 'toffee_core' },
            { id: 2, label: '토피넛', value: 'toffee_nut' },
            { id: 3, label: '토피크런치', value: 'toffee_crunch' },
            { id: 4, label: '토피소스', value: 'toffee_sauce' },
            { id: 5, label: '버터토피', value: 'butter_toffee' },
          ],
        },
        {
          id: 3,
          label: '버터스카치',
          value: 'butterscotch',
          children: [
            { id: 1, label: '버터스카치', value: 'butterscotch_core' },
            { id: 2, label: '버터스카치소스', value: 'butterscotch_sauce' },
            { id: 3, label: '버터스카치캔디', value: 'butterscotch_candy' },
            { id: 4, label: '스카치토피', value: 'scotch_toffee' },
            { id: 5, label: '브라운버터', value: 'brown_butter' },
          ],
        },
        {
          id: 4,
          label: '브륄레',
          value: 'brulee',
          children: [
            { id: 1, label: '크렘브륄레', value: 'creme_brulee' },
            { id: 2, label: '설탕크러스트', value: 'sugar_crust' },
            { id: 3, label: '카라멜화설탕', value: 'caramelized_sugar' },
            { id: 4, label: '카라멜푸딩', value: 'caramel_pudding' },
            { id: 5, label: '카라멜크림브륄레', value: 'caramel_cream_brulee' },
          ],
        },
        {
          id: 5,
          label: '구운당미',
          value: 'toasted_sweet',
          children: [
            { id: 1, label: '로스티드마시멜로', value: 'roasted_marshmallow' },
            { id: 2, label: '카라멜팝콘', value: 'caramel_popcorn' },
            { id: 3, label: '토스트슈거', value: 'toasted_sugar' },
            { id: 4, label: '브라운슈가노트', value: 'brown_sugar_note' },
            { id: 5, label: '몰트스위트', value: 'malt_sweet' },
          ],
        },
      ],
    },
    {
      id: 3,
      label: '허니',
      value: 'switness_honeyed',
      children: [
        {
          id: 1,
          label: '라이트허니',
          value: 'light_honey',
          children: [
            { id: 1, label: '아카시아꿀', value: 'acacia_honey' },
            { id: 2, label: '클로버꿀', value: 'clover_honey' },
            { id: 3, label: '오렌지블로섬꿀', value: 'orange_blossom_honey' },
            { id: 4, label: '라임블로섬꿀', value: 'lime_blossom_honey' },
            { id: 5, label: '라이트와일드플라워', value: 'light_wildflower_honey' },
          ],
        },
        {
          id: 2,
          label: '다크허니',
          value: 'dark_honey',
          children: [
            { id: 1, label: '밤꿀', value: 'chestnut_honey' },
            { id: 2, label: '메밀꿀', value: 'buckwheat_honey' },
            { id: 3, label: '유칼립투스꿀', value: 'eucalyptus_honey' },
            { id: 4, label: '마누카꿀', value: 'manuka_honey' },
            { id: 5, label: '소나무꿀', value: 'pine_honey' },
          ],
        },
        {
          id: 3,
          label: '허니디저트',
          value: 'honey_dessert',
          children: [
            { id: 1, label: '허니버터', value: 'honey_butter' },
            { id: 2, label: '허니쿠키', value: 'honey_cookie' },
            { id: 3, label: '허니케이크', value: 'honey_cake' },
            { id: 4, label: '허니글레이즈', value: 'honey_glaze' },
            { id: 5, label: '허니그래놀라', value: 'honey_granola' },
          ],
        },
        {
          id: 4,
          label: '허니음료',
          value: 'honey_drink',
          children: [
            { id: 1, label: '허니레몬티', value: 'honey_lemon_tea' },
            { id: 2, label: '허니우롱티', value: 'honey_oolong_tea' },
            { id: 3, label: '허니라떼', value: 'honey_latte' },
            { id: 4, label: '허니주스', value: 'honey_juice' },
            { id: 5, label: '허니자몽티', value: 'honey_grapefruit_tea' },
          ],
        },
        {
          id: 5,
          label: '벌집·왁스',
          value: 'comb_wax',
          children: [
            { id: 1, label: '벌집꿀', value: 'honeycomb' },
            { id: 2, label: '비즈왁스', value: 'beeswax' },
            { id: 3, label: '꽃가루', value: 'bee_pollen' },
            { id: 4, label: '프로폴리스', value: 'propolis' },
            { id: 5, label: '로열젤리', value: 'royal_jelly' },
          ],
        },
      ],
    },
    {
      id: 4,
      label: '과일단맛',
      value: 'switness_fruity',
      children: [
        {
          id: 1,
          label: '시트러스스위트',
          value: 'citrus_sweet',
          children: [
            { id: 1, label: '오렌지마멀레이드', value: 'orange_marmalade' },
            { id: 2, label: '레몬커드', value: 'lemon_curd' },
            { id: 3, label: '유자청', value: 'yuja_marmalade' },
            { id: 4, label: '라임시럽', value: 'lime_syrup' },
            { id: 5, label: '만다린캔디', value: 'mandarin_candy' },
          ],
        },
        {
          id: 2,
          label: '베리스위트',
          value: 'berry_sweet',
          children: [
            { id: 1, label: '딸기잼', value: 'strawberry_jam' },
            { id: 2, label: '라즈베리잼', value: 'raspberry_jam' },
            { id: 3, label: '블루베리시럽', value: 'blueberry_syrup' },
            { id: 4, label: '블랙베리콤포트', value: 'blackberry_compote' },
            { id: 5, label: '크랜베리소스', value: 'cranberry_sauce' },
          ],
        },
        {
          id: 3,
          label: '트로피컬스위트',
          value: 'tropical_sweet',
          children: [
            { id: 1, label: '망고퓨레', value: 'mango_puree' },
            { id: 2, label: '파인애플시럽', value: 'pineapple_syrup' },
            { id: 3, label: '바나나칩스위트', value: 'banana_chip_sweet' },
            { id: 4, label: '코코넛크림스위트', value: 'coconut_cream_sweet' },
            { id: 5, label: '패션프루트시럽', value: 'passionfruit_syrup' },
          ],
        },
        {
          id: 4,
          label: '스톤프루트스위트',
          value: 'stonefruit_sweet',
          children: [
            { id: 1, label: '복숭아시럽', value: 'peach_syrup' },
            { id: 2, label: '살구잼', value: 'apricot_jam' },
            { id: 3, label: '자두콤포트', value: 'plum_compote' },
            { id: 4, label: '체리시럽', value: 'cherry_syrup' },
            { id: 5, label: '넥타린퓨레', value: 'nectarine_puree' },
          ],
        },
        {
          id: 5,
          label: '건과일스위트',
          value: 'driedfruit_sweet',
          children: [
            { id: 1, label: '건포도', value: 'raisin' },
            { id: 2, label: '말린살구', value: 'dried_apricot' },
            { id: 3, label: '무화과', value: 'fig' },
            { id: 4, label: '대추', value: 'jujube' },
            { id: 5, label: '대추야자시럽', value: 'date_syrup' },
          ],
        },
      ],
    },
    {
      id: 5,
      label: '디저트',
      value: 'switness_confectionery',
      children: [
        {
          id: 1,
          label: '크림·커스터드',
          value: 'cream_custard',
          children: [
            { id: 1, label: '바닐라크림', value: 'vanilla_cream' },
            { id: 2, label: '커스터드', value: 'custard' },
            { id: 3, label: '휘핑크림', value: 'whipped_cream' },
            { id: 4, label: '크렘앙글레즈', value: 'creme_anglaise' },
            { id: 5, label: '파나코타', value: 'panna_cotta' },
          ],
        },
        {
          id: 2,
          label: '베이커리',
          value: 'bakery',
          children: [
            { id: 1, label: '스폰지케이크', value: 'sponge_cake' },
            { id: 2, label: '쇼트브레드', value: 'shortbread' },
            { id: 3, label: '브리오슈', value: 'brioche' },
            { id: 4, label: '도넛글레이즈', value: 'donut_glaze' },
            { id: 5, label: '바닐라빈케이크', value: 'vanilla_bean_cake' },
          ],
        },
        {
          id: 3,
          label: '초콜릿류',
          value: 'chocolate_sweet',
          children: [
            { id: 1, label: '밀크초콜릿', value: 'milk_chocolate' },
            { id: 2, label: '화이트초콜릿', value: 'white_chocolate' },
            { id: 3, label: '헤이즐넛스프레드', value: 'hazelnut_spread' },
            { id: 4, label: '코코아', value: 'cocoa' },
            { id: 5, label: '카라멜초콜릿', value: 'caramel_chocolate' },
          ],
        },
        {
          id: 4,
          label: '설탕과자',
          value: 'sugar_confection',
          children: [
            { id: 1, label: '터키시딜라이트', value: 'turkish_delight' },
            { id: 2, label: '프랄린', value: 'praline' },
            { id: 3, label: '브리틀', value: 'brittle' },
            { id: 4, label: '캔디드넛', value: 'candied_nut' },
            { id: 5, label: '누가', value: 'nougat' },
          ],
        },
        {
          id: 5,
          label: '시럽·토핑',
          value: 'syrup_topping',
          children: [
            { id: 1, label: '메이플시럽', value: 'maple_syrup' },
            { id: 2, label: '초콜릿시럽', value: 'chocolate_syrup' },
            { id: 3, label: '바닐라시럽', value: 'vanilla_syrup' },
            { id: 4, label: '스트로베리소스', value: 'strawberry_sauce' },
            { id: 5, label: '헤이즐넛시럽', value: 'hazelnut_syrup' },
          ],
        },
      ],
    },
  ],
  mouthfeel: [
    {
      id: 1,
      label: '질감',
      value: 'mouthfeel_texture',
      children: [
        {
          id: 1,
          label: '라이트',
          value: 'light',
          children: [
            { id: 1, label: '얇은', value: 'thin' },
            { id: 2, label: '가벼운', value: 'delicate' },
            { id: 3, label: '부드러운', value: 'soft' },
            { id: 4, label: '산뜻한', value: 'refreshing' },
            { id: 5, label: '맑은', value: 'clear' },
          ],
        },
        {
          id: 2,
          label: '미디엄',
          value: 'medium',
          children: [
            { id: 1, label: '균형잡힌', value: 'balanced' },
            { id: 2, label: '라운디드', value: 'rounded' },
            { id: 3, label: '탄탄한', value: 'firm' },
            { id: 4, label: '매끄러운', value: 'smooth' },
            { id: 5, label: '적당한', value: 'moderate' },
          ],
        },
        {
          id: 3,
          label: '풀',
          value: 'full',
          children: [
            { id: 1, label: '묵직한', value: 'heavy' },
            { id: 2, label: '시럽같은', value: 'syrupy' },
            { id: 3, label: '점성있는', value: 'viscous' },
            { id: 4, label: '오일리한', value: 'oily' },
            { id: 5, label: '버터리한', value: 'buttery' },
          ],
        },
        {
          id: 4,
          label: '크리미',
          value: 'creamy',
          children: [
            { id: 1, label: '밀크같은', value: 'milky' },
            { id: 2, label: '벨벳같은', value: 'velvety' },
            { id: 3, label: '실키한', value: 'silky' },
            { id: 4, label: '부드러운', value: 'gentle' },
            { id: 5, label: '농밀한', value: 'dense' },
          ],
        },
        {
          id: 5,
          label: '거친',
          value: 'rough',
          children: [
            { id: 1, label: '거칠은', value: 'coarse' },
            { id: 2, label: '거품성', value: 'foamy' },
            { id: 3, label: '모래알같은', value: 'grainy' },
            { id: 4, label: '거친산미', value: 'harsh_acid' },
            { id: 5, label: '울퉁불퉁한', value: 'rugged' },
          ],
        },
      ],
    },
    {
      id: 2,
      label: '밀도감',
      value: 'mouthfeel_density',
      children: [
        {
          id: 1,
          label: '얇은밀도',
          value: 'thin_density',
          children: [
            { id: 1, label: '희석된', value: 'diluted' },
            { id: 2, label: '가벼운', value: 'light_body' },
            { id: 3, label: '밋밋한', value: 'flat' },
            { id: 4, label: '단순한', value: 'simple' },
            { id: 5, label: '산뜻한', value: 'clean' },
          ],
        },
        {
          id: 2,
          label: '중간밀도',
          value: 'medium_density',
          children: [
            { id: 1, label: '균형잡힌', value: 'balanced_body' },
            { id: 2, label: '탄탄한', value: 'solid' },
            { id: 3, label: '풍부한', value: 'rich' },
            { id: 4, label: '조화로운', value: 'harmonious' },
            { id: 5, label: '적당히점성있는', value: 'moderately_viscous' },
          ],
        },
        {
          id: 3,
          label: '높은밀도',
          value: 'high_density',
          children: [
            { id: 1, label: '묵직한', value: 'heavy_body' },
            { id: 2, label: '점성높은', value: 'high_viscosity' },
            { id: 3, label: '리치한', value: 'rich_texture' },
            { id: 4, label: '진득한', value: 'thick' },
            { id: 5, label: '포화감있는', value: 'saturated' },
          ],
        },
        {
          id: 4,
          label: '점성',
          value: 'viscosity',
          children: [
            { id: 1, label: '시럽같은', value: 'syrupy' },
            { id: 2, label: '오일리한', value: 'oily' },
            { id: 3, label: '끈적한', value: 'sticky' },
            { id: 4, label: '농후한', value: 'dense_texture' },
            { id: 5, label: '점도가있는', value: 'viscous' },
          ],
        },
        {
          id: 5,
          label: '공기감',
          value: 'airy',
          children: [
            { id: 1, label: '거품감있는', value: 'foamy_texture' },
            { id: 2, label: '가볍게부풀은', value: 'fluffy' },
            { id: 3, label: '통기성있는', value: 'airy' },
            { id: 4, label: '산뜻한', value: 'fresh' },
            { id: 5, label: '깨끗한', value: 'clear_mouthfeel' },
          ],
        },
      ],
    },
    {
      id: 3,
      label: '잔류감',
      value: 'mouthfeel_afterfeel',
      children: [
        {
          id: 1,
          label: '클린',
          value: 'clean_finish',
          children: [
            { id: 1, label: '깔끔한', value: 'clean' },
            { id: 2, label: '짧은여운', value: 'short_finish' },
            { id: 3, label: '상쾌한', value: 'refreshing' },
            { id: 4, label: '맑은', value: 'transparent' },
            { id: 5, label: '밝은', value: 'bright' },
          ],
        },
        {
          id: 2,
          label: '롱피니시',
          value: 'long_finish',
          children: [
            { id: 1, label: '지속적인', value: 'lingering' },
            { id: 2, label: '풍부한여운', value: 'long_aftertaste' },
            { id: 3, label: '감칠맛있는', value: 'umami_finish' },
            { id: 4, label: '깊은', value: 'deep' },
            { id: 5, label: '잔잔한', value: 'gentle_finish' },
          ],
        },
        {
          id: 3,
          label: '드라이',
          value: 'dry_finish',
          children: [
            { id: 1, label: '드라이한', value: 'dry' },
            { id: 2, label: '약간수축되는', value: 'astringent' },
            { id: 3, label: '타닌감', value: 'tannic' },
            { id: 4, label: '바삭한', value: 'crisp_finish' },
            { id: 5, label: '깨끗하게끝남', value: 'clean_end' },
          ],
        },
        {
          id: 4,
          label: '스위트피니시',
          value: 'sweet_finish',
          children: [
            { id: 1, label: '은은한단맛', value: 'subtle_sweet' },
            { id: 2, label: '꿀여운', value: 'honey_aftertaste' },
            { id: 3, label: '부드러운끝', value: 'soft_finish' },
            { id: 4, label: '둥근여운', value: 'rounded_finish' },
            { id: 5, label: '균형잡힌여운', value: 'balanced_finish' },
          ],
        },
        {
          id: 5,
          label: '쓴여운',
          value: 'bitter_finish',
          children: [
            { id: 1, label: '가벼운쓴미', value: 'light_bitter' },
            { id: 2, label: '허벌한잔류', value: 'herbal_finish' },
            { id: 3, label: '로스티드감', value: 'roasted_finish' },
            { id: 4, label: '초콜릿여운', value: 'choco_finish' },
            { id: 5, label: '홉느낌', value: 'hop_like' },
          ],
        },
      ],
    },
    {
      id: 4,
      label: '온도감',
      value: 'mouthfeel_temperature',
      children: [
        {
          id: 1,
          label: '따뜻한',
          value: 'warm',
          children: [
            { id: 1, label: '부드러운온기', value: 'gentle_warmth' },
            { id: 2, label: '은은한따뜻함', value: 'mild_heat' },
            { id: 3, label: '편안한', value: 'comforting' },
            { id: 4, label: '균형있는온기', value: 'balanced_heat' },
            { id: 5, label: '따뜻한입감', value: 'warm_body' },
          ],
        },
        {
          id: 2,
          label: '뜨거운',
          value: 'hot',
          children: [
            { id: 1, label: '강한열감', value: 'strong_heat' },
            { id: 2, label: '입안자극', value: 'mouth_burn' },
            { id: 3, label: '매운온도감', value: 'spicy_heat' },
            { id: 4, label: '알코올감', value: 'alcohol_heat' },
            { id: 5, label: '강렬한온도감', value: 'intense_heat' },
          ],
        },
        {
          id: 3,
          label: '차가운',
          value: 'cold',
          children: [
            { id: 1, label: '시원한', value: 'cool' },
            { id: 2, label: '멘톨감', value: 'menthol' },
            { id: 3, label: '프레시', value: 'fresh' },
            { id: 4, label: '클린쿨링', value: 'clean_cooling' },
            { id: 5, label: '얼음느낌', value: 'icy' },
          ],
        },
        {
          id: 4,
          label: '미묘한온도',
          value: 'subtle_temp',
          children: [
            { id: 1, label: '미세한온기', value: 'faint_warm' },
            { id: 2, label: '약한쿨링', value: 'mild_cool' },
            { id: 3, label: '중립적', value: 'neutral' },
            { id: 4, label: '안정된', value: 'stable' },
            { id: 5, label: '균형된온도감', value: 'balanced_temp' },
          ],
        },
        {
          id: 5,
          label: '열-쿨 밸런스',
          value: 'thermal_balance',
          children: [
            { id: 1, label: '균형있는', value: 'balanced' },
            { id: 2, label: '동시감각', value: 'dual_sensation' },
            { id: 3, label: '복합감', value: 'complex_temp' },
            { id: 4, label: '조화로운', value: 'harmonious' },
            { id: 5, label: '미묘한온감', value: 'subtle_thermal' },
          ],
        },
      ],
    },
    {
      id: 5,
      label: '촉감',
      value: 'mouthfeel_tactile',
      children: [
        {
          id: 1,
          label: '탄산감',
          value: 'carbonation',
          children: [
            { id: 1, label: '미세기포', value: 'fine_bubble' },
            { id: 2, label: '중간기포', value: 'medium_bubble' },
            { id: 3, label: '거친기포', value: 'large_bubble' },
            { id: 4, label: '스파클링감', value: 'sparkling' },
            { id: 5, label: '톡쏘는', value: 'tingling' },
          ],
        },
        {
          id: 2,
          label: '수렴감',
          value: 'astringency',
          children: [
            { id: 1, label: '약한수렴감', value: 'light_astringency' },
            { id: 2, label: '중간수렴감', value: 'medium_astringency' },
            { id: 3, label: '강한수렴감', value: 'strong_astringency' },
            { id: 4, label: '입안수축감', value: 'mouth_contraction' },
            { id: 5, label: '드라이한촉감', value: 'dry_tactile' },
          ],
        },
        {
          id: 3,
          label: '점착감',
          value: 'stickiness',
          children: [
            { id: 1, label: '끈적한', value: 'sticky' },
            { id: 2, label: '약간점착', value: 'slightly_sticky' },
            { id: 3, label: '농밀한', value: 'dense_stick' },
            { id: 4, label: '부드럽게달라붙는', value: 'soft_cling' },
            { id: 5, label: '시럽성', value: 'syrupy_stick' },
          ],
        },
        {
          id: 4,
          label: '청량감',
          value: 'refreshing_tactile',
          children: [
            { id: 1, label: '시원한감촉', value: 'cool_touch' },
            { id: 2, label: '멘톨감', value: 'menthol_touch' },
            { id: 3, label: '깨끗한촉감', value: 'clean_touch' },
            { id: 4, label: '산뜻한', value: 'fresh_tactile' },
            { id: 5, label: '가벼운쿨링', value: 'light_cooling' },
          ],
        },
        {
          id: 5,
          label: '거친촉감',
          value: 'rough_tactile',
          children: [
            { id: 1, label: '거친', value: 'rough' },
            { id: 2, label: '분말감', value: 'powdery' },
            { id: 3, label: '모래감', value: 'gritty' },
            { id: 4, label: '입자감', value: 'grainy' },
            { id: 5, label: '두꺼운입자감', value: 'coarse_particle' },
          ],
        },
      ],
    },
  ],
};
