const a = {
  id: 2,
  title: '맛 평가',
  explanation: '커피를 시음하는 과정에서 느낀점들을 평가해주세요.',
  single_selections: [
    { id: 1, label: '향미', range: 3, selected: 1 },
    { id: 2, label: '뒷맛(애프터테이스트)', range: 3, selected: 2 },
  ],
  multiple_selections: [
    {
      id: 1,
      title: '해당되는 기술어',
      limit: 5,
      items: [
        { id: 101, parentId: null, label: '꽃', selected: true },
        { id: 201, parentId: null, label: '과일', selected: true },
        { id: 202, parentId: 201, label: '베리', selected: false },
        { id: 203, parentId: 201, label: '말린 과일', selected: true },
        { id: 204, parentId: 201, label: '감귤류', selected: false },
        { id: 301, parentId: null, label: '신/발효된', selected: false },
        { id: 302, parentId: 301, label: '신맛', selected: false },
        { id: 303, parentId: 301, label: '발효된', selected: false },
        { id: 401, parentId: null, label: '녹색채소/식물성', selected: false },
        { id: 501, parentId: null, label: '기타', selected: true },
        { id: 502, parentId: 501, label: '화학적인', selected: false },
        { id: 503, parentId: 501, label: '퀴퀴한/흙냄새', selected: false },
        { id: 504, parentId: 501, label: '종이같은', selected: true },
        { id: 601, parentId: null, label: '구운', selected: false },
        { id: 701, parentId: null, label: '견과류/코코아', selected: true },
        { id: 702, parentId: 701, label: '견과류', selected: true },
        { id: 703, parentId: 701, label: '코코아', selected: false },
        { id: 801, parentId: null, label: '향신료', selected: false },
        { id: 901, parentId: null, label: '달콤한', selected: true },
        { id: 902, parentId: 901, label: '바닐라/바닐린', selected: true },
        { id: 903, parentId: 901, label: '황설탕(브라운슈거)', selected: false },
      ],
    },
    {
      id: 2,
      title: '주요 맛',
      limit: 2,
      items: [
        { id: 1001, parentId: null, label: '짠맛', selected: true },
        { id: 1101, parentId: null, label: '신맛', selected: false },
        { id: 1201, parentId: null, label: '단맛', selected: false },
        { id: 1301, parentId: null, label: '쓴맛', selected: true },
        { id: 1401, parentId: null, label: '감칠맛', selected: false },
      ],
    },
  ],
  affective_explanation: '품질에 대한 개인적인 인상과 의견을 남겨주세요.',
  tooltips: [
    '극히 낮음',
    '매우 낮음',
    '적당히 낮음',
    '약간 낮음',
    '높지도 낮지도 않음',
    '약간 높음',
    '적당히 높음',
    '매우 높음',
    '극히 높음',
  ],
  affective_assessments: [
    { id: 1, sort: 10, type: 'slider', label: '프레그런스', min: 1, max: 9, selected: 1 },
    { id: 2, sort: 20, type: 'slider', label: '아로마', min: 1, max: 9, selected: 1 },
  ],
  affective_comment: {
    type: 'textarea',
    placeholder: '개인적인 의견을 입력해주세요.',
    comment: '',
  },
};
